"""create lands and documents

Revision ID: f28bef5d7d7f
Revises: 
Create Date: 2026-10-08 21:04:06.424895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28bef5d7d7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lands',
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('upazila', sa.String(), nullable=False),
    sa.Column('mouza', sa.String(), nullable=False),
    sa.Column('dag_no', sa.String(), nullable=False),
    sa.Column('khatian_no', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('land_id', sa.Uuid(), nullable=True),
    sa.Column('doc_type', sa.Enum('khatian', 'deed', 'dcr', 'heir_cert', 'other', name='doctype'), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'done', 'failed', name='docstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['lands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('lands')
    # ### end Alembic commands ###
    sa.Enum(name='docstatus').drop(op.get_bind())
    sa.Enum(name='doctype').drop(op.get_bind())
